language: node_js
node_js: '12'
sudo: enabled
dist: trusty
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
install:
  - npm ci
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
os:
  - linux
  - osx
  - windows
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev-i386
      - gcc-multilib
      - g++-multilib
      - ninja-build
      - linux-libc-dev:i386
      - linux-libc-dev
      - icnsutils
      - graphicsmagick
      - libsecret-1-dev

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run compile-darwin ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run compile-linux ;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run compile-win32 ;fi
